name: build-cpp

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        configuration: ['Debug', 'Release']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create CMake build files
        working-directory: ${{github.workspace}}
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        run: |
          cmake -B build

      - name: Compile the project
        working-directory: ${{github.workspace}}
        run: |
          cmake --build build --config ${{ matrix.configuration }} -j8

      - name: Run the tests
        working-directory: ${{github.workspace}}/build
        run: |
          ctest
